### ISSUE TITLE
VPN speed

### ISSUE THREAD

**Issue by pascalandy** [kolargol/openvpn#3]
I'm taking a huge hit on the speed using exoscale micro vps. 
Do you have other servers to propose outside America? 

## NO VPN
<img width="401" alt="screen shot 2017-08-28 at 11 28 32 pm" src="https://user-images.githubusercontent.com/6694151/29803336-f35c60f0-8c48-11e7-9de6-4f702152e88d.png">

## WITH VPN
<img width="397" alt="screen shot 2017-08-28 at 11 29 26 pm" src="https://user-images.githubusercontent.com/6694151/29803335-f35a0fd0-8c48-11e7-83cd-85919a315c7a.png">

**Comment by kolargol** [comment]
Yes, exoscale uses Equinix as a backend datacenter and it's solely Europe oriented company that's why your transfers can be low. You can try to lower encryption (as mentioned in readme default settings are quite overkill but despite that, transfers should not be impaired more then 20% according to my tests, so when you get 100Mbps after tunneling you got 80Mbps)
Try find some other providers, Azure have support for OpenBSD as well (https://azure.microsoft.com/en-us/blog/running-openbsd-on-azure/), you can setup your own OpenBSD on OVH (https://www.tumfatig.net/20161124/encrypted-openbsd-6-0-in-the-ovh-cloud/) See also this page: https://bsdvm.com they have some selections of cloud providers with freeBSD and OpenBSD

**Comment by kolargol** [comment]
Can you please compare UDP-branch ?

**Comment by pascalandy** [comment]
on my todo

**Comment by kolargol** [comment]
you can try https://www.vultr.com that offer IPv6 and is spread across globe

**Comment by pascalandy** [comment]
I tried on Vultr but the provisioning didn't work. Do you confirm it works?

**Comment by kolargol** [comment]
yes i have deployed it many times. do you have more details what do not work? did you opened udp ports for udp-branch?

**Comment by pascalandy** [comment]
First, thank you very much for your patience. I appreciate it a lot!!

The issue was that my SSH key wrong. 

Using the branch `udp-branch` I'm getting fantastic results. Officially my connection is a 120/20. Now I don't see any difference between running behind the VPN or not!!

I will use this setup for few days. Then I'll retest the master branch. 
Many cheers!

<img width="724" alt="screen shot 2017-09-04 at 11 39 15 am" src="https://user-images.githubusercontent.com/6694151/30032909-3ec1d760-9166-11e7-8b65-f76d27c44afc.png">
<img width="724" alt="screen shot 2017-09-04 at 11 33 52 am" src="https://user-images.githubusercontent.com/6694151/30032910-3ec22670-9166-11e7-86f6-9f5fed309d20.png">
<img width="789" alt="screen shot 2017-09-04 at 11 39 48 am" src="https://user-images.githubusercontent.com/6694151/30032911-3ec568ee-9166-11e7-8643-932a871c373a.png">
<img width="1153" alt="screen shot 2017-09-04 at 11 38 18 am" src="https://user-images.githubusercontent.com/6694151/30032913-3ec75780-9166-11e7-83fd-863508e8aca5.png">
<img width="779" alt="screen shot 2017-09-04 at 11 34 56 am" src="https://user-images.githubusercontent.com/6694151/30032912-3ec6cb4e-9166-11e7-8c13-d920b591db43.png">

**Comment by kolargol** [comment]
I am glad I could help. UDP branch is much faster indeed
